param([Parameter(Mandatory=$true)][string]$InputFile)
$ErrorActionPreference='Stop'
$sourceRoot=Split-Path -Parent $MyInvocation.MyCommand.Path;$root=$env:HF_DASHBOARD_ROOT;if([string]::IsNullOrWhiteSpace($root)){$root=$sourceRoot}
$statusFile=Join-Path $root 'nct-status.json';$lockFile=Join-Path $root 'nct-update.lock';$portableNode=Join-Path $sourceRoot 'runtime\node\node.exe';$node=if(Test-Path -LiteralPath $portableNode){$portableNode}else{(Get-Command node -ErrorAction SilentlyContinue).Source};if([string]::IsNullOrWhiteSpace($node)){$node='C:\Users\user\.cache\codex-runtimes\codex-primary-runtime\dependencies\node\bin\node.exe'}
$script=Join-Path $sourceRoot 'sync-nct-table.mjs';$startedAt=Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
function Write-NctStatus($state,$message,$detail=''){$payload=[ordered]@{state=[string]$state;message=[string]$message;detail=[string]$detail;time=(Get-Date -Format 'yyyy-MM-dd HH:mm:ss');startedAt=$startedAt}|ConvertTo-Json -Compress;[IO.File]::WriteAllText($statusFile,$payload,[Text.UTF8Encoding]::new($false))}
$lockStream=$null
$completed=$false
try{$lockStream=[IO.File]::Open($lockFile,[IO.FileMode]::OpenOrCreate,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None);if(-not(Test-Path -LiteralPath $node)){throw '未找到本地Node.js运行环境。'};if(-not(Test-Path -LiteralPath $script)){throw '未找到NCT年卡写入脚本。'};if(-not(Test-Path -LiteralPath $InputFile)){throw '未收到当前Chrome的NCT订单数据。'};Write-NctStatus 'running' '正在写入钉钉“年卡招考数据”子表…' '旧数据在写入并校验成功前保持不变';$previous=$ErrorActionPreference;$ErrorActionPreference='Continue';$output=@(& $node $script $InputFile 2>&1|ForEach-Object{[string]$_});$exitCode=$LASTEXITCODE;$ErrorActionPreference=$previous;$text=($output-join"`n").Trim();if($exitCode-ne0){$line=(($text-split"`r?`n")|Where-Object{$_}|Select-Object -First 1);if($line.Length-gt240){$line=$line.Substring(0,240)+'…'};throw $line};$crm=[regex]::Match($text,'NCT_CRM_OK rows=(\d+) columns=(\d+)');$sync=[regex]::Match($text,'NCT_SYNC_OK rows=(\d+)');if(-not$crm.Success-or-not$sync.Success){throw 'NCT订单写入完成标记缺失，未判定为成功。'};$completed=$true;Write-NctStatus 'success' 'NCT年卡购买数据更新完成' "CRM $($crm.Groups[1].Value) 条 · 已写入 $($sync.Groups[1].Value) 条 · 子表：年卡招考数据"}catch{Write-NctStatus 'error' 'NCT年卡购买数据更新失败' $_.Exception.Message;exit 1}finally{if($null-ne$lockStream){$lockStream.Dispose()};if($completed-and(Test-Path -LiteralPath $InputFile)){Remove-Item -LiteralPath $InputFile -Force -ErrorAction SilentlyContinue}}
